[project]
name = "tp4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "moderngl>=5.11.1",
    "PyGLM>=2.7.3",
    "numpy>=2.2.1",
    "pyglet>=2.1.3"
]
